-- 상품사진 → SKU image_url (재적용/보정). V14의 단지 조인이 운영에서 stock 미연결 SKU를 놓쳐
-- (품목+규격)만으로 매칭. (product_name,spec) 는 전역 유일이므로 안전. 멱등.
SET NAMES utf8mb4;

UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/149.jpg' WHERE product_name='V벨트' AND spec='B-84/DONGIL';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/150.jpg' WHERE product_name='V벨트' AND spec='B-113/DONGIL';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/151.jpg' WHERE product_name='V벨트' AND spec='B-120/DONGIL';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/152.jpg' WHERE product_name='V벨트' AND spec='B-101/MITUBOSHI';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/153.jpg' WHERE product_name='V벨트' AND spec='B-101/DONGIL';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/154.jpg' WHERE product_name='V벨트' AND spec='R4B/DONGIL';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/155.jpg' WHERE product_name='V벨트' AND spec='W-1118/Continental';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/156.jpg' WHERE product_name='V벨트' AND spec='B-126/DONGIL';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/157.jpg' WHERE product_name='V벨트' AND spec='B-107/DONGIL';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/158.jpg' WHERE product_name='V벨트' AND spec='D16S 12/MITUBOSHI';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/159.jpg' WHERE product_name='V벨트' AND spec='A28/DONGIL';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/160.jpg' WHERE product_name='V벨트' AND spec='B-115/DONGIL';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/161.jpg' WHERE product_name='대변기 세척벨브' AND spec='FC110CS(세트)';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/162.jpg' WHERE product_name='대변기 푸쉬버튼' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/163.jpg' WHERE product_name='대변기 피스톤' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/164.jpg' WHERE product_name='레벨스위치' AND spec='KFS-PC8';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/165.jpg' WHERE product_name='멀티 조인트 커플링' AND spec='80A';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/166.jpg' WHERE product_name='멀티 조인트 커플링' AND spec='100A';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/167.jpg' WHERE product_name='멀티 조인트 커플링' AND spec='40A,18kgf';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/168.jpg' WHERE product_name='멀티 조인트 커플링' AND spec='40A,16kgf';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/169.jpg' WHERE product_name='멀티 조인트 커플링' AND spec='40A,20kgf';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/170.jpg' WHERE product_name='배관 테이프' AND spec='회색';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/171.jpg' WHERE product_name='배관 테이프' AND spec='파랑';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/172.jpg' WHERE product_name='배관 테이프' AND spec='노랑';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/173.jpg' WHERE product_name='버터플라이 벨브' AND spec='80A';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/174.jpg' WHERE product_name='변거커버 볼트&너트' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/175.jpg' WHERE product_name='볼벨브' AND spec='40A';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/176.jpg' WHERE product_name='볼벨브' AND spec='32A';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/177.jpg' WHERE product_name='볼벨브' AND spec='20A';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/178.jpg' WHERE product_name='세면대 트랩' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/179.jpg' WHERE product_name='세면대 폼업대' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/180.jpg' WHERE product_name='세면용 수전' AND spec='MA-1720';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/181.jpg' WHERE product_name='세면용 수전' AND spec='DLYL6A10CA1';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/182.jpg' WHERE product_name='소변기 센서' AND spec='FU-5117/512T/구형';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/183.jpg' WHERE product_name='소변기 솔벨브' AND spec='MLV-6(구형)';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/184.jpg' WHERE product_name='소변기마개' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/185.jpg' WHERE product_name='수도꼭지' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/186.jpg' WHERE product_name='열선' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/187.jpg' WHERE product_name='오뚜기센서(플로트스위치)' AND spec='투라인레벨 (세트)';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/188.jpg' WHERE product_name='오뚜기센서(플로트스위치)' AND spec='SOODUK(수덕)';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/189.jpg' WHERE product_name='오뚜기센서(플로트스위치)' AND spec='일신센서';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/190.jpg' WHERE product_name='원격 온수미터' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/191.jpg' WHERE product_name='자동문 체인' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/192.jpg' WHERE product_name='체크벨브' AND spec='10K/80A';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/193.jpg' WHERE product_name='화장실 문 경첩' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/194.jpg' WHERE product_name='화장실 문 손잡이' AND spec='os-230';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/195.jpg' WHERE product_name='화장실 문 옷걸이' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/234.jpg' WHERE product_name='3m장갑 슈퍼그립200' AND spec='m';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/235.jpg' WHERE product_name='opp테이프/투명' AND spec='48*38m';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/236.jpg' WHERE product_name='PVC 본드' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/237.jpg' WHERE product_name='VCTF 2.5*3C' AND spec='M';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/238.jpg' WHERE product_name='WD-40' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/239.jpg' WHERE product_name='걸고리' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/240.jpg' WHERE product_name='검전기(특고압)' AND spec='AC80-30KV';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/241.jpg' WHERE product_name='고도 급결 방수제' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/242.jpg' WHERE product_name='그리스' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/243.jpg' WHERE product_name='넝마집게/환경집게' AND spec='700mm';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/244.jpg' WHERE product_name='덕트 테이프' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/245.jpg' WHERE product_name='도로반사경' AND spec='800mm';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/246.jpg' WHERE product_name='도료용 희석제' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/247.jpg' WHERE product_name='도어스토퍼' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/248.jpg' WHERE product_name='드라이버비트bw212' AND spec='2*65mm';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/249.jpg' WHERE product_name='락카' AND spec='검정';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/250.jpg' WHERE product_name='락카' AND spec='백색';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/251.jpg' WHERE product_name='락카신너(일반용)' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/252.jpg' WHERE product_name='롤러(로라)' AND spec='대';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/253.jpg' WHERE product_name='롤러(로라)' AND spec='중';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/254.jpg' WHERE product_name='롤러(로라)' AND spec='소';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/255.jpg' WHERE product_name='마스킹테이프' AND spec='48*40m';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/256.jpg' WHERE product_name='미끄럼방지 테이프' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/257.jpg' WHERE product_name='반사 테이프' AND spec='노랑';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/258.jpg' WHERE product_name='반사 테이프' AND spec='형광';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/259.jpg' WHERE product_name='반코팅 장갑' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/260.jpg' WHERE product_name='방화문 도어락 손잡이' AND spec='9000 BALL';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/261.jpg' WHERE product_name='번호키 도어락' AND spec='G707S GateTop';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/262.jpg' WHERE product_name='번호키 도어락 걸쇠' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/263.jpg' WHERE product_name='스티커 제거제' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/264.jpg' WHERE product_name='실리콘' AND spec='투명/무초산형';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/265.jpg' WHERE product_name='실리콘' AND spec='백색/비초산형';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/266.jpg' WHERE product_name='실리콘' AND spec='백색/일반건축용씰링';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/267.jpg' WHERE product_name='실리콘' AND spec='회색/무초산형';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/268.jpg' WHERE product_name='실리콘' AND spec='회색/건축용1액형우레탄실란트';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/269.jpg' WHERE product_name='실리콘' AND spec='검정/FixAll(틈새충진용)';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/270.jpg' WHERE product_name='안전 제일 테이프' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/271.jpg' WHERE product_name='에니탄 I DAU-508 흑색(주제)' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/272.jpg' WHERE product_name='에니탄(경화제)(무황변)' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/273.jpg' WHERE product_name='에니탄(주제)(황색)' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/274.jpg' WHERE product_name='에니탄2740(경화제)' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/275.jpg' WHERE product_name='에폭시 만능 프라이머(경화제)' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/276.jpg' WHERE product_name='에폭시 만능 프라이머(주제)(백색)' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/277.jpg' WHERE product_name='오일스탠' AND spec='투명';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/278.jpg' WHERE product_name='우레탄 신너' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/279.jpg' WHERE product_name='우레탄 폼 클리너' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/280.jpg' WHERE product_name='우레판 폼' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/281.jpg' WHERE product_name='주차장 기둥 보호대' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/282.jpg' WHERE product_name='청테이프' AND spec='48mm*7m';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/283.jpg' WHERE product_name='카 스토퍼' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/284.jpg' WHERE product_name='커터칼' AND spec='18mm';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/285.jpg' WHERE product_name='탄력봉' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/286.jpg' WHERE product_name='테프론테이프' AND spec='12.7mm*0.075*10m';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/287.jpg' WHERE product_name='텍스' AND spec='12mm/ 300mm x 600mm';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/288.jpg' WHERE product_name='텍스' AND spec='9.5mm/ 300mm x 600mm';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/289.jpg' WHERE product_name='페인트' AND spec='백색';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/290.jpg' WHERE product_name='페인트 붓' AND spec='2''''';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/291.jpg' WHERE product_name='페인트 붓' AND spec='3''''';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/292.jpg' WHERE product_name='페인트 붓' AND spec='4''''';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/293.jpg' WHERE product_name='페인트풋' AND spec='1 1/2''''';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/294.jpg' WHERE product_name='페인트풋' AND spec='1/2''''';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/295.jpg' WHERE product_name='플로어 힌지' AND spec='K8500';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/296.jpg' WHERE product_name='플로어 힌지' AND spec='K-9700';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/368.jpg' WHERE product_name='소변기자동세척기' AND spec='그린컨트롤';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/369.jpg' WHERE product_name='수도꼭지' AND spec='20A';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/370.jpg' WHERE product_name='화재감지기' AND spec='차동식스포트형';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/371.jpg' WHERE product_name='목공용톱날' AND spec='330mm';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/372.jpg' WHERE product_name='문빗장' AND spec='화장실용';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/373.jpg' WHERE product_name='문손잡이' AND spec='화장실용';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/374.jpg' WHERE product_name='물비누공급기' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/375.jpg' WHERE product_name='슈퍼그립200 장갑' AND spec='대';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/376.jpg' WHERE product_name='슈퍼그립201 장갑' AND spec='중';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/377.jpg' WHERE product_name='장대톱날' AND spec='340mm';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/378.jpg' WHERE product_name='2구 스위치' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/379.jpg' WHERE product_name='8핀타이머' AND spec='용성';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/380.jpg' WHERE product_name='8핀타이머' AND spec='오토닉스';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/381.jpg' WHERE product_name='LED램프' AND spec='150W';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/382.jpg' WHERE product_name='건전지' AND spec='AAA';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/383.jpg' WHERE product_name='건전지' AND spec='AA';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/384.jpg' WHERE product_name='노출스위치박스' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/385.jpg' WHERE product_name='누전차단기' AND spec='20A';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/386.jpg' WHERE product_name='누전차단기' AND spec='30A';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/387.jpg' WHERE product_name='누전차단기' AND spec='40A';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/388.jpg' WHERE product_name='누전차단기' AND spec='75A';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/389.jpg' WHERE product_name='릴레이' AND spec='5A';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/390.jpg' WHERE product_name='맹커버' AND spec='';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/391.jpg' WHERE product_name='메탈핼라이드램프' AND spec='250W';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/392.jpg' WHERE product_name='안정기' AND spec='250W';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/393.jpg' WHERE product_name='전구' AND spec='화장실용';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/394.jpg' WHERE product_name='전력용콘덴서' AND spec='40KV';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/395.jpg' WHERE product_name='전자접촉기' AND spec='MC-12b';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/396.jpg' WHERE product_name='전자접촉기' AND spec='MC-22b';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/397.jpg' WHERE product_name='타이머' AND spec='SMT-30A';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/398.jpg' WHERE product_name='푸쉬버튼스위치' AND spec='DLL-1110';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/399.jpg' WHERE product_name='플로트스위치' AND spec='1m';
UPDATE skus SET image_url='https://dwe-on-mpark.s3.ap-northeast-2.amazonaws.com/mpark/stock/image/product/400.jpg' WHERE product_name='하이박스' AND spec='150*200';
